### ISSUE TITLE
Skin cases

### ISSUE THREAD

**Issue by afeistel** [OnGoTeam/TMGmod#17]
- [x] Skin
~~Module~~

**Comment by timotheyca** [comment]
```
-  0  1  2  3  4
0 D0 C1 C2 C3 C4
1 CV ML HM WR MA
```

**Comment by timotheyca** [comment]
C1 dated wine
C2 yellow
C3 dark cyan
C4 Red

**Comment by EXsess** [comment]
Ещё сюда добавить новогодний кейс, в котором будет новогоднее оружие. Вот.
Там типа Ёлка, леденец и тд (я придумаю)

**Comment by EXsess** [comment]
Скинов Red(1):
- [x] SIX12
- [x] SIX12S
- [x] Daewoo K1
- [x] AUG A3
- [x] AUG A1
- [x] Skeet Gun
- [x] PPSH [DEBUG]
- [x] PPSHC [DEBUG]
- [x] PPSh 41
- [x] PPK 42
- [x] HK417
- [x] Vintorez
- [x] VSK-94
- [x] PMR-30
- [x] 50AE Pistol
- [x] SKS
- [x] SRM1208

--17--

**Comment by EXsess** [comment]
Скинов Blue(2):

- [x] SIX12
- [x] SIX12S
- [x] Daewoo K1
- [x] Uzi Pro
- [x] MP5
- [x] MP5SD
- [x] AWS
- [x] USP
- [x] 50AE Pistol
- [x] Vista
- [x] DragoShot
- [x] AUG A1
- [x] PPSh 41
- [x] PPK 42
- [x] SKS
- [x] SRM1208

--16--

**Comment by EXsess** [comment]
Скинов Cyan(3):

- [x] SIX12
- [x] SIX12S
- [x] Daewoo K1
- [x] MP5
- [x] MP5SD
- [x] USP
- [x] CZ805
- [x] AF2011
- [x] MG44
- [x] Lynx
- [x] SV99
- [x] PPSh 41
- [x] PPK 42
- [x] SKS
- [x] TC-12

--15--

**Comment by EXsess** [comment]
Скинов Yellow(4):

- [x] SIX12
- [x] SIX12S
- [x] Daewoo K1
- [x] Uzi Pro
- [x] MP5
- [x] MP5SD
- [x] AWS
- [x] CZ805
- [x] USP
- [x] Skeet Gun
- [x] ALFA
- [x] SMG-9
- [x] AUG A1
- [x] PPSh 41
- [x] PPK 42
- [x] SKS

--16--

**Comment by EXsess** [comment]
Скинов Prismarine(6):

- [x] SIX12
- [x] SIX12S
- [x] ARX200
- [x] Uzi Pro
- [x] PPSH [DEBUG]
- [x] PPSHC [DEBUG]
- [x] PPSh 41
- [x] PPK 42
- [x] MG44
- [x] Skeet Gun
- [x] MP5
- [x] MP5SD
- [x] AWS
- [x] AN-94
- [x] AUG
- [x] Vixr
- [x] Spectre M4
- [x] SKS

--18--

**Comment by EXsess** [comment]
Скинов Nitro(7):

- [x] USP
- [x] AWS
- [x] Daewoo K1
- [x] SIX12
- [x] SIX12S
- [x] MG44
- [x] MP5
- [x] MP5SD
- [x] PPSH [DEBUG]
- [x] PPSHC [DEBUG]
- [x] PPSh 41
- [x] PPK 42
- [x] Skeet Gun
- [x] Vintorez
- [x] VSK-94
- [x] 50AE Pistol
- [x] AN-94C
- [x] Type 89
- [x] ARX200
- [x] FCAR
- [x] RFB
- [x] HazeS
- [x] AA12
- [x] MP40
- [x] SKS

--25--

**Comment by EXsess** [comment]
Ещё остались места 5 и 9, но их можно сделать больше, если потребуется

**Comment by EXsess** [comment]
Скинов Green(8):

- [x] AUG A1
- [x] AUG A3
- [x] AA12
- [x] DragoShot
- [x] MP40
- [x] PPSH [DEBUG]
- [x] PPSHC [DEBUG]
- [x] PPSh 41
- [x] PPK 42
- [x] SV98
- [x] SV99
- [x] SRM1208
- [x] SKS
- [x] AWS

--12--
