### ISSUE TITLE
Новое Guns в 1.1.2

### ISSUE THREAD

**Issue by EXsess** [OnGoTeam/TMGmod#57]
- [x] Оставить СВУ только с обычным магазином, остальные заменить на что-то подобное
- [x] СВУ с маленьким магазином >>> M14 с магазином на 10 патрон и дикой отдачей
- [x] СВУ с большим магазином >>> IB-8mm Sniper с магазином на ~~40~~ 20 патрон, но большим разбросом (ПП с тупа дикой дальностью)
- [x] Alep-30 (Вместо глока с увеличенным магазином)
- [x] Experimental ANP-73 (по механике - ваг, по виду - что-то нормальное)
- [x] Experimental X3X (просто перерисованный X3X)
- [x] SRM 1208 (вместо ТР-21)
- [x] AA-12 (вместо ТР-21 с большим магом)
- [x] ВСК-94 (вместо винтореза с большим магазином)[больше отдача, скорострельность, но меньше дальность]
- [x] ARW-A (вместо AKwAR̆). У неё (него?) будет выпадать магазин, когда кончатся патроны. 
- [x] ARWAMAG 
- [x] ПП-19 Бизон (вместо P90)
- [x] Сделать нормальный ППШ (не удалять старый, он прекрасен)
- [x] Вместо нормального ППШ с маленьким магазином - ППК-42
     ~M16A6 (ааэ оно подбросит вас до арбата за 1 сек)~ Будет в 1.2
- [x] AR15, которая будет взрываться вместо M4A1 (она не будет больше взрываться). А ещё магаз 20. И взрыв не убивает утку, которая её держит. Также взрывается если попытаться выстрелить с пустым магазином. 
- [x] G9M - аналогично, но пулемёт и с сошками. Маг - 70.

**Comment by afeistel** [comment]
Перерисовать akwar и перенести скрипт в basegun #19; то же с cz75

**Comment by afeistel** [comment]
16/16
