### ISSUE TITLE
Последние штрихи в 1.1.2

### ISSUE THREAD

**Issue by EXsess** [OnGoTeam/TMGmod#68]
Нужно сделать вот что:
- [x] Сделать так, что при переключении на гранатомёт SCAR GL, Flare менялся на FlareBase1.png и потом обратно на FlareOnePixel2.png
- [x] Переписать X3X так, чтобы у него затвор сразу отъезжал назад после выстрела.

**Comment by afeistel** [comment]
683de48

**Comment by afeistel** [comment]
bf78aad
